const ROLES = {
  CUSTOMER: 'CUSTOMER',
  PROVIDER: 'PROVIDER',
  ADMIN: 'ADMIN'
};
const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
};
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};
const PAYMENT_METHODS = {
  CARD: 'CARD',
  UPI: 'UPI',
  NETBANKING: 'NETBANKING',
  CASH: 'CASH',
  WALLET: 'WALLET'
};
const NOTIFICATION_TYPES = {
  BOOKING: 'BOOKING',
  MESSAGE: 'MESSAGE',
  PAYMENT: 'PAYMENT',
  SYSTEM: 'SYSTEM',
  REMINDER: 'REMINDER'
};
const DOCUMENT_TYPES = {
  BILL: 'BILL',
  WARRANTY: 'WARRANTY',
  MANUAL: 'MANUAL',
  AMC: 'AMC'
};
const REMINDER_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE'
};
const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};
const COMPLAINT_STATUS = {
  OPEN: 'OPEN',
  IN_INVESTIGATION: 'IN_INVESTIGATION',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};
module.exports = {
  ROLES,
  BOOKING_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  NOTIFICATION_TYPES,
  DOCUMENT_TYPES,
  REMINDER_STATUS,
  COMPLAINT_PRIORITY,
  COMPLAINT_STATUS
};
